INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (1, 'Penerbitan dan Percetakan', 1, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (2, 'Microsoft Azure', 4, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (3, 'Penyedia Perencana dan detil', 16, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (4, 'Manajemen Konstruksi', 17, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (5, 'pelaksana konstruksi', 18, 2);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (6, 'koleksi e-book', 20, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (7, 'alat peraga', 2, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (8, 'Renewal Lisensi Microsoft', 5, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (9, 'interior', 19, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (10, 'ijazah', 21, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (11, 'Pemeliharaan Komputer', 8, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (12, 'konveksi', 23, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (13, 'iklan', 26, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (14, 'boga', 29, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (15, 'kargo', 35, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (16, 'building', 36, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (17, 'Konsultan Sistem Informatika', 10, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (18, 'Jasa Konsultan Sistem Informatika', 13, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (19, 'Komputer dan Peripheral', 9, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (20, 'alat tulis kantor', 25, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (21, 'elektronik', 24, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (22, 'obat', 30, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (23, 'Internet dan VPN', 7, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (24, 'satpam', 37, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (25, 'pengharum', 38, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (26, 'pest control', 39, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (27, 'Pengembangan Mutu', 45, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (28, 'Outsourcing', 46, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (29, 'Pemeliharaan system', 11, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (30, 'sewa gedung', 47, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (31, 'layout', 3, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (32, 'mice', 27, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (33, 'Prasarana', 48, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (34, 'Digital Signage', 12, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (35, 'sdm', 49, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (36, 'Pelaksana  Konstruksi', 18, 2);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (37, 'jasa konstruksi', 18, 2);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (38, 'Jasa Perencana', 16, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (39, 'Amnities', 31, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (40, 'laundry', 32, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (41, 'Pemeliharaan Peralatan', 40, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (42, 'Perhotelan', 50, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (43, 'merchandise', 28, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (44, 'Penerjemahan', 57, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (45, 'linen', 33, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (46, 'Mekanikal', 40, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (47, 'Pemeliharaan Gedung', 41, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (48, 'Jasa Multimedia', 58, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (49, 'asuransi', 51, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (50, 'sewa Cloud Server', 6, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (51, 'Konsultan Bisnis', 59, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (52, 'fiber optik', 14, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (53, 'Leasing', 52, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (54, 'tanah', 53, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (55, 'dekorasi Taman', 34, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (56, 'Konsultan Perencanaan Teknis', 16, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (57, 'forklift', 43, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (58, 'Kantor Akuntan Publik', 60, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (59, 'konsultan kap', 60, 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (60, 'Sayembara', 55, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (61, 'Peralatan Mesin Kantor', 42, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (62, 'Laboratorium', 61, 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (63, 'Perawatan Perlengkapan', 40, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (64, 'Penyedia Konstruksi', 18, 2);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (65, 'Keperluan Pesta', 22, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (66, 'lelang', 56, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (67, 'dokumentasi foto', 62, 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori", "kode_jenis_pengadaan") VALUES (68, 'Telekomunikasi', 15, 1);
