INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (3, 'Penyedia Perencana dan detil', 16);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (7, 'alat peraga', 2);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (6, 'koleksi e-book', 20);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (5, 'pelaksana konstruksi', 18);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (4, 'Manajemen Konstruksi', 17);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (2, 'Microsoft Azure', 4);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (8, 'Renewal Lisensi Microsoft', 5);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (9, 'interior', 19);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (10, 'ijazah', 21);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (11, 'Pemeliharaan Komputer', 8);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (12, 'konveksi', 23);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (13, 'iklan', 26);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (14, 'boga', 29);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (15, 'kargo', 35);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (16, 'building', 36);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (17, 'Konsultan Sistem Informatika', 10);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (18, 'Jasa Konsultan Sistem Informatika', 13);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (19, 'Komputer dan Peripheral', 9);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (20, 'alat tulis kantor', 25);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (21, 'elektronik', 24);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (22, 'obat', 30);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (23, 'Internet dan VPN', 7);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (24, 'satpam', 37);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (25, 'pengharum', 38);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (26, 'pest control', 39);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (27, 'Pengembangan Mutu', 45);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (28, 'Outsourcing', 46);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (29, 'Pemeliharaan system', 11);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (30, 'sewa gedung', 47);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (31, 'layout', 3);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (32, 'mice', 27);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (33, 'Prasarana', 48);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (34, 'Digital Signage', 12);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (35, 'sdm', 49);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (36, 'Pelaksana  Konstruksi', 18);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (37, 'jasa konstruksi', 18);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (38, 'Jasa Perencana', 16);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (39, 'Amnities', 31);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (40, 'laundry', 32);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (41, 'Pemeliharaan Peralatan', 40);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (42, 'Perhotelan', 50);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (43, 'merchandise', 28);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (44, 'Penerjemahan', 57);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (45, 'linen', 33);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (46, 'Mekanikal', 40);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (47, 'Pemeliharaan Gedung', 41);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (48, 'Jasa Multimedia', 58);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (1, 'Penerbitan dan Percetakan', 1);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (49, 'asuransi', 51);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (50, 'sewa Cloud Server', 6);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (51, 'Konsultan Bisnis', 59);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (52, 'fiber optik', 14);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (53, 'Leasing', 52);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (54, 'tanah', 53);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (55, 'dekorasi Taman', 34);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (56, 'Konsultan Perencanaan Teknis', 16);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (57, 'forklift', 43);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (58, 'Kantor Akuntan Publik', 60);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (59, 'konsultan kap', 60);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (60, 'Sayembara', 55);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (61, 'Peralatan Mesin Kantor', 42);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (62, 'Laboratorium', 61);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (63, 'Perawatan Perlengkapan', 40);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (64, 'Penyedia Konstruksi', 18);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (65, 'Keperluan Pesta', 22);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (66, 'lelang', 56);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (67, 'dokumentasi foto', 62);
INSERT INTO "public"."helper_kategori_kw" ("id", "keyword", "kode_kategori") VALUES (68, 'Telekomunikasi', 15);
