-- ref_kategori;
INSERT INTO "public"."ref_kategori" VALUES (1, 'Penyedia Jasa Penerbitan dan Percetakan');
INSERT INTO "public"."ref_kategori" VALUES (2, 'Penyedia Peralatan Alat Peraga Pendidikan');
INSERT INTO "public"."ref_kategori" VALUES (3, 'Penyedia Jasa Layout Bahan Ajar');
INSERT INTO "public"."ref_kategori" VALUES (4, 'Penyedia Cloud Server');
INSERT INTO "public"."ref_kategori" VALUES (5, 'Penyedia Renewal Lisensi Microsoft');
INSERT INTO "public"."ref_kategori" VALUES (6, 'Penyedia Jasa Sewa Cloud Server');
INSERT INTO "public"."ref_kategori" VALUES (7, 'Penyedia Jasa Layanan Internet dan VPN');
INSERT INTO "public"."ref_kategori" VALUES (8, 'Penyedia Jasa Pemeliharaan Komputer');
INSERT INTO "public"."ref_kategori" VALUES (9, 'Penyedia Komputer dan Peripheral');
INSERT INTO "public"."ref_kategori" VALUES (10, 'Penyedia Konsultan Sistem Informatika');
INSERT INTO "public"."ref_kategori" VALUES (11, 'Penyedia Jasa Pemeliharaan System');
INSERT INTO "public"."ref_kategori" VALUES (12, 'Penyedia Digital Signage');
INSERT INTO "public"."ref_kategori" VALUES (13, 'Penyedia Jasa Konsultan Sistem Informatika');
INSERT INTO "public"."ref_kategori" VALUES (14, 'Penyedia Jasa Installasi Fiber Optik');
INSERT INTO "public"."ref_kategori" VALUES (15, 'Penyedia Alat Telekomunikasi');
INSERT INTO "public"."ref_kategori" VALUES (16, 'Penyedia Jasa Konsultan Perencana dan Detail Desain Pembangunan Gedung');
INSERT INTO "public"."ref_kategori" VALUES (17, 'Penyedia Jasa Konsultan Manajemen Konstruksi (MK)');
INSERT INTO "public"."ref_kategori" VALUES (18, 'Penyedia Pelaksana Konstruksi');
INSERT INTO "public"."ref_kategori" VALUES (19, 'Penyedia Interior dan Furniture');
INSERT INTO "public"."ref_kategori" VALUES (20, 'Penyedia Koleksi E-Book, E-Journal dan Buku Teks');
INSERT INTO "public"."ref_kategori" VALUES (21, 'Penyedia Pencetakan Blangko Ijazah/Sertifikat/Transkrip');
INSERT INTO "public"."ref_kategori" VALUES (22, 'Penyedia Jasa Sewa Alat Keperluan Pesta');
INSERT INTO "public"."ref_kategori" VALUES (23, 'Penyedia Jasa Konveksi');
INSERT INTO "public"."ref_kategori" VALUES (24, 'Penyedia Alat Elektronik dan Kerumahtanggaan');
INSERT INTO "public"."ref_kategori" VALUES (25, 'Penyedia Alat Tulis Kantor');
INSERT INTO "public"."ref_kategori" VALUES (26, 'Penyedia Jasa Periklanan');
INSERT INTO "public"."ref_kategori" VALUES (27, 'Penyedia Jasa Event Organizer UT Pusat');
INSERT INTO "public"."ref_kategori" VALUES (28, 'Penyedia Merchandise UT');
INSERT INTO "public"."ref_kategori" VALUES (29, 'Penyedia Jasa Boga');
INSERT INTO "public"."ref_kategori" VALUES (30, 'Penyedia Obat dan Alat Kesehatan');
INSERT INTO "public"."ref_kategori" VALUES (31, 'Penyedia Amnities');
INSERT INTO "public"."ref_kategori" VALUES (32, 'Penyedia Jasa Laundry');
INSERT INTO "public"."ref_kategori" VALUES (33, 'Penyedia Linen');
INSERT INTO "public"."ref_kategori" VALUES (34, 'Penyedia Jasa Dekorasi Taman');
INSERT INTO "public"."ref_kategori" VALUES (35, 'Penyedia Jasa Pengiriman');
INSERT INTO "public"."ref_kategori" VALUES (36, 'Penyedia Building Management');
INSERT INTO "public"."ref_kategori" VALUES (37, 'Penyedia Jasa Satuan Pengaman (SATPAM)');
INSERT INTO "public"."ref_kategori" VALUES (38, 'Penyedia Jasa Sewa Pengharum Ruangan dan Toilet Sanitizer');
INSERT INTO "public"."ref_kategori" VALUES (39, 'Penyedia Jasa Pest Control');
INSERT INTO "public"."ref_kategori" VALUES (40, 'Penyedia Jasa Pemeliharaan Peralatan Mesin dan Perawatan Perlengkapan Kerumahtanggan');
INSERT INTO "public"."ref_kategori" VALUES (41, 'Penyedia Jasa Pemeliharaan Gedung UT');
INSERT INTO "public"."ref_kategori" VALUES (42, 'Penyedia Sewa Peralatan Mesin');
INSERT INTO "public"."ref_kategori" VALUES (43, 'Penyedia Jasa Sewa Forklift');
INSERT INTO "public"."ref_kategori" VALUES (44, 'Penyedia Solar Panel');
INSERT INTO "public"."ref_kategori" VALUES (45, 'Penyedia Jasa Konsultan Pengembangan Mutu Pendidikan');
INSERT INTO "public"."ref_kategori" VALUES (46, 'Penyedia Jasa Outsourcing');
INSERT INTO "public"."ref_kategori" VALUES (47, 'Penyedia Sewa Gedung ');
INSERT INTO "public"."ref_kategori" VALUES (48, 'Penyedia Sarana Prasarana');
INSERT INTO "public"."ref_kategori" VALUES (49, 'Penyedia Jasa Konsultan Pengembangan SDM');
INSERT INTO "public"."ref_kategori" VALUES (50, 'Penyedia Jasa Perhotelan');
INSERT INTO "public"."ref_kategori" VALUES (51, 'Penyedia Jasa Asuransi');
INSERT INTO "public"."ref_kategori" VALUES (52, 'Penyedia Jasa Leasing');
INSERT INTO "public"."ref_kategori" VALUES (53, 'Penyedia Pengadaan Tanah');
INSERT INTO "public"."ref_kategori" VALUES (54, 'Penyedia Jasa Notaris');
INSERT INTO "public"."ref_kategori" VALUES (55, 'Penyelenggaraan Kegiatan Sayembara');
INSERT INTO "public"."ref_kategori" VALUES (56, 'Penyedia Jasa Penilai dan Lelang');
INSERT INTO "public"."ref_kategori" VALUES (57, 'Penyedia Jasa Penerjemahan');
INSERT INTO "public"."ref_kategori" VALUES (58, 'Penyedia Jasa Multimedia');
INSERT INTO "public"."ref_kategori" VALUES (59, 'Penyedia Jasa Konsultan Bisnis');
INSERT INTO "public"."ref_kategori" VALUES (60, 'Penyedia Jasa Konsultan Kantor Akuntan Publik');
INSERT INTO "public"."ref_kategori" VALUES (61, 'Penyedia Alat Laboratorium');
INSERT INTO "public"."ref_kategori" VALUES (62, 'Penyedia Jasa Dokumentasi Foto');